apiVersion: v1
kind: Service
metadata:
  name: messaging
  labels:
    app: amq-interconnect
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: qdr-external-cert
spec:
  ports:
  - port: 5671
    name: amqps
  - port: 5672
    name: amqp
  - port: 8672
    name: console
  selector:
    type: qdrouterd
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: amq-interconnect
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: amq-interconnect
        version: v1
        type: qdrouterd
    spec:
      containers:
      - name: amq-interconnect
        env:
        - name: AMQ_LOCATION_KEY
          value: ONPREM
        - name: ONPREM_SUFFIX
          value: ${ONPREM_SUFFIX}
        - name: AWS_SUFFIX
          value: ${AWS_SUFFIX}
        - name: GCP_SUFFIX
          value: ${GCP_SUFFIX}
        - name: AZURE_SUFFIX
          value: ${AZURE_SUFFIX}
        image: tedross/qpid-dispatch-router:1.2.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5672
          protocol: TCP
        volumeMounts:
        - name: qdr-config
          mountPath: /etc/qpid-dispatch
        - name: internal-certs
          readOnly: true
          mountPath: /etc/qpid-dispatch-certs/internal
      volumes:
      - name: qdr-config
        configMap:
          name: qdr-config
      - name: internal-certs
        secret:
          secretName: qdr-internal-cert
---
apiVersion: v1
kind: Route
metadata:
  name: amqps
spec:
  host: amqps-demo2-amq.apps.${ONPREM_SUFFIX}
  port:
    targetPort: amqps
  tls:
    termination: passthrough
  to:
    kind: Service
    name: messaging
    weight: 100
  wildcardPolicy: None
---
apiVersion: v1
kind: Route
metadata:
  name: console
spec:
  host: console-demo2-amq.apps.${ONPREM_SUFFIX}
  port:
    targetPort: console
  to:
    kind: Service
    name: messaging
    weight: 100
  wildcardPolicy: None
